stages:
  - deploy-production
deploy-production:
  stage: deploy-production
  environment:
    name: Production
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no borisey@95.142.39.128
      'cd /var/www/html/cutli.ru && git pull origin main'
    - $MAVEN_HOME/bin/mvn clean compile
    - $MAVEN_HOME/bin/mvn package
    - java -jar target/link-shortener-0.0.1-SNAPSHOT.jar --server.port=80